### ISSUE TITLE
"unsupported kv version" when using kubernetes auth method

### ISSUE THREAD

**Issue by wouterhummelink** [bakito/vault-unsealer#250]
I'm trying to get unsealer to work with the keys stored within vault so that reloader can unseal as long as one remains up.
Kubernetes auth seems to be working correctly. I see 200 replies to /v1/sys/mounts and /v1/auth/kubernetes/login

output of `vault read /sys/mounts`
```
kv/           map[accessor:kv_809f910c config:map[default_lease_ttl:0 force_no_cache:false max_lease_ttl:0] deprecation_status:supported description: external_entropy_access:false local:false options:map[version:2] plugin_version: running_plugin_version:v0.21.0+builtin running_sha256: seal_wrap:false type:kv uuid:76a95bc8-32c9-f260-bad8-93fa544c1b50]
```

Secret used to configure unsealer
```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    vault-unsealer.bakito.net/stateful-set: vault
  name: vault-unsealer-config-kubernetes
type: Opaque
stringData:
  role: unseal
  mountPath:  kubernetes
  secretPath: kv2/unsealKeys
```
